ALTER TYPE "TruckType" ADD VALUE IF NOT EXISTS 'SMALL';
ALTER TYPE "TruckType" ADD VALUE IF NOT EXISTS 'MEDIUM';
ALTER TYPE "TruckType" ADD VALUE IF NOT EXISTS 'TEN_TON';
ALTER TYPE "TruckType" ADD VALUE IF NOT EXISTS 'BANN';
